 "use client";
import {useState} from "react";
const products=[["🥛","Молоко","8×"],["🍌","Бананы","7×"],["🥚","Яйца","6×"],["🍗","Курица","5×"]];
const deals=[["Куриное филе","€5.99/kg","−30%"],["Яйца 10 шт.","€2.49","−16%"],["Кофе 500 g","€5.99","−29%"]];
export default function Home(){
 const [tab,setTab]=useState("home"); const [items,setItems]=useState(["Молоко","Яйца","Бананы","Куриное филе","Сыр"]); const [input,setInput]=useState("");
 const add=()=>{if(input.trim()){setItems([...items,input.trim()]);setInput("")}};
 return <div className="app"><aside><div className="logo">🛒 My Grocery</div>{[["home","⌂ Главная"],["receipts","▣ Чеки"],["analytics","◔ Аналитика"],["cart","🛒 Моя корзина"],["prices","↕ Цены и акции"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</aside>
 <main><header><div><h1>{tab==="home"?"Добрый день 👋":({receipts:"Чеки",analytics:"Аналитика",cart:"Моя корзина",prices:"Цены и акции"} as any)[tab]}</h1><p>Твой персональный помощник по продуктам</p></div><div className="avatar">Д</div></header>
 {tab==="home"&&<><div className="cards">{[["Потрачено в октябре","€284.62","↓ 8% к среднему"],["Средний чек","€42.80","за последние 3 месяца"],["Можно сэкономить сейчас","€7.40","на обычной корзине"]].map(x=><div className="card"><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="two"><section><h2>🔥 Сейчас выгодно купить</h2>{deals.map(x=><div className="row"><span>{x[0]}</span><b>{x[1]} <em>{x[2]}</em></b></div>)}</section><section><h2>⭐ Твои частые покупки</h2>{products.map(x=><div className="row"><span>{x[0]} {x[1]}</span><b>{x[2]}</b></div>)}</section></div><section><h2>📷 Добавить покупку</h2><label className="upload">Выбрать фото чека<input type="file" accept="image/*"/></label><p className="note">В следующей версии фото будет автоматически распознаваться и превращаться в список покупок.</p></section></>}
 {tab==="receipts"&&<section><h2>Последние чеки</h2><table><thead><tr><th>Дата</th><th>Магазин</th><th>Позиций</th><th>Сумма</th></tr></thead><tbody>{[["05.10.2026","Rimi","23","€48.32"],["29.09.2026","Maxima","19","€37.81"],["22.09.2026","Prisma","28","€54.20"],["15.09.2026","Rimi","21","€41.62"]].map(r=><tr>{r.map(c=><td>{c}</td>)}</tr>)}</tbody></table></section>}
 {tab==="analytics"&&<><div className="two"><section><h2>Расходы по категориям</h2>{[["🥩 Мясо","€62.80"],["🥛 Молочные","€47.20"],["🥦 Овощи","€38.40"],["🍌 Фрукты","€29.60"],["🍫 Сладости","€22.10"]].map(x=><div className="row"><span>{x[0]}</span><b>{x[1]}</b></div>)}</section><section><h2>🔮 Что скоро понадобится</h2><p className="note">🥚 Яйца — обычно каждые 12 дней, прошло 11.</p><p className="note">☕ Кофе — обычно каждые 27 дней, прошло 25.</p></section></div></>}
 {tab==="cart"&&<><div className="two"><section><h2>🛒 Твоя корзина</h2>{items.map((x,i)=><div className="row"><span>{x}</span><button onClick={()=>setItems(items.filter((_,j)=>j!==i))}>×</button></div>)}<div className="add"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Добавить продукт…"/><button onClick={add}>+</button></div><button className="primary" onClick={()=>alert("Демонстрация: Maxima €26.00 — самый выгодный вариант")}>Где дешевле?</button></section><section><h2>💡 Оптимальный вариант</h2><div className="store best"><b>🥇 Maxima</b><strong>€26.00</strong><p>Экономия примерно €5.20</p></div><div className="store">🥈 Rimi <strong>€29.10</strong></div><div className="store">🥉 Prisma <strong>€30.70</strong></div></section></div></>}
 {tab==="prices"&&<div className="two">{["Maxima","Rimi","Selver","Prisma"].map(s=><section><h2>{s}</h2><div className="row"><span>Куриное филе</span><b>€5.99/kg</b></div><div className="row"><span>Яйца 10 шт.</span><b>€2.49</b></div><p className="note">Демонстрационные данные. Реальные цены подключим отдельно.</p></section>)}</div>}
 </main></div>
}
